env: pybullet.TableEnv
env_kwargs:
  name: pick
  gui: true

  primitives:
    - pick

  tasks:
    - action_skeleton:
        - pick(table_box_1, table)
      initial_state:
        - free(table_box_1)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(table_box_1)
        - on(rack, table)
        - on(hook, table)
        - on(table_box_1, table)
        - on(table_box_2, table)
        - on(table_box_3, table)
        - on(table_box_4, table)
        - on(rack_box_1, rack)
        - on(rack_box_2, rack)
        - on(rack_box_3, rack)
        - on(rack_box_4, rack)
    - action_skeleton:
        - pick(hook, table)
      initial_state:
        - free(hook)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(hook)
        - on(rack, table)
        - on(hook, table)
        - on(table_box_1, table)
        - on(table_box_2, table)
        - on(table_box_3, table)
        - on(table_box_4, table)
        - on(rack_box_1, rack)
        - on(rack_box_2, rack)
        - on(rack_box_3, rack)
        - on(rack_box_4, rack)

  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  object_groups:
    - name: boxes
      objects:
        - configs/pybullet/envs/assets/salt.yaml
        - configs/pybullet/envs/assets/milk.yaml
        - configs/pybullet/envs/assets/yogurt.yaml
        - configs/pybullet/envs/assets/icecream.yaml
        - object_type: Null
        - object_type: Null
        - object_type: Null
        - object_type: Null
        - object_type: Null
        - object_type: Null
        - object_type: Null
        - object_type: Null

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Variant
      object_kwargs:
        name: rack
        variants:
          - object_type: Rack
            object_kwargs:
              size: [0.22, 0.32, 0.16]
              color: [0.4, 0.2, 0.0, 1.0]
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: hook
        variants:
          - object_type: Hook
            object_kwargs:
              head_length: 0.2
              handle_length: 0.38
              handle_y: -1.0
              color: [0.6, 0.6, 0.6, 1.0]
          - object_type: Null
    - object_type: Variant
      object_kwargs:
        name: table_box_1
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: table_box_2
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: table_box_3
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: table_box_4
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: rack_box_1
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: rack_box_2
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: rack_box_3
        group: boxes
    - object_type: Variant
      object_kwargs:
        name: rack_box_4
        group: boxes
