trainer: AgentTrainer
trainer_kwargs:
  dataset_class: ReplayBuffer
  dataset_kwargs:
    capacity: 500000
    batch_size: 128
    sample_strategy: uniform
    save_frequency: 1000
  
  optimizer_class: Adam
  optimizer_kwargs:
    lr: 0.0001

  num_pretrain_steps: 500000
  num_train_steps: 1000000
  num_eval_episodes: 100
  eval_freq: 1000
  checkpoint_freq: 50000
  log_freq: 1000
  profile_freq: 1000
