trainer: ValueTrainer
trainer_kwargs:
  dataset_class: ReplayBuffer
  dataset_kwargs:
    capacity: 1600000
    batch_size: 128
    sample_strategy: uniform
  eval_dataset_kwargs:
    capacity: 400000
    batch_size: 128
    sample_strategy: uniform

  optimizer_class: Adam
  optimizer_kwargs:
    lr: 0.0001

  scheduler_class: CosineAnnealingLR
  scheduler_kwargs:
    T_max: 2500000

  num_train_steps: 2500000
  num_eval_episodes: 1000
  eval_freq: 10000
  checkpoint_freq: 100000
  log_freq: 1000
  profile_freq: 100
