agent: EnsembleAgent
agent_kwargs:
  # EnsembleLogitOODCritic wrapper configuration.
  critic_class: EnsembleLogitOODCritic
  ood_threshold: 0.0
  pessimistic: true

  # SAC Configuration.
  agent_config: 
    agent: SAC
    agent_kwargs:
      tau: 0.005
      initial_temperature: 0.1
      critic_update_freq: 1
      actor_update_freq: 0
      target_update_freq: 0
      use_bce: true

      actor_class: actors.DiagonalGaussianMLPActor
      actor_kwargs:
        hidden_layers: [256, 256]
        log_std_bounds: [-5, 2]
        ortho_init: true

      critic_class: critics.ContinuousMLPCritic
      critic_kwargs:
        hidden_layers: [256, 256]
        num_q_fns: 8
        ortho_init: true
        output_act: Sigmoid

      encoder_class: encoders.TableEnvEncoder
