env: pybullet.TableEnv
env_kwargs:
  name: hook_reach_1
  gui: true

  primitives:
    - pick
    - place
    - pull
    - push

  tasks:
    - action_skeleton:
        - pick(hook, table)
        - pull(yellow_box, hook)
        - place(hook, table)
        - pick(yellow_box, table)
        - place(yellow_box, rack)
      initial_state:
        - free(hook)
        - free(yellow_box)
        - free(blue_box)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(rack)
        - inworkspace(hook)
        - beyondworkspace(yellow_box)
        - nonblocking(yellow_box, rack)
        - nonblocking(yellow_box, blue_box)
        - on(rack, table)
        - on(hook, table)
        - on(yellow_box, table)
        - on(blue_box, table)
        
  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - configs/pybullet/envs/assets/salt.yaml
    - configs/pybullet/envs/assets/yogurt.yaml

