planner: ShootingPlanner
planner_kwargs:
  num_samples: 1000

agent_configs:
  - agent: GaussianAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
      std: 0.3
  - agent: GaussianAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
      std: 0.3
  - agent: GaussianAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
      std: 0.3
  - agent: GaussianAgent
    agent_kwargs:
      agent_config: "{AGENT_CONFIG}"
      std: 0.3

dynamics_config:
  dynamics: OracleDynamics
  dynamics_kwargs:
    debug: false
