planner: CEMPlanner
planner_kwargs:
  num_samples: 200
  num_iterations: 5
  num_elites: 10
  standard_deviation: 0.3

agent_configs:
  - agent: RandomAgent
    agent_kwargs:
      agent_config:
        agent: OracleAgent
        agent_kwargs:
          agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config:
        agent: OracleAgent
        agent_kwargs:
          agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config:
        agent: OracleAgent
        agent_kwargs:
          agent_config: "{AGENT_CONFIG}"
  - agent: RandomAgent
    agent_kwargs:
      agent_config:
        agent: OracleAgent
        agent_kwargs:
          agent_config: "{AGENT_CONFIG}"

dynamics_config:
  dynamics: OracleDynamics
